### ISSUE TITLE
assert failure when an element is a bool

### ISSUE THREAD

**Issue by mean-ui-thread** [Lunarsong/StructureOfArrays#7]
```C++
SoA<bool> test;
```
creates the following error
```
StructureOfArrays/soa.h:175: error: static assertion failed: Structure of Array assumes of vector<Type> is same size as vector<void*> however the assumption failed.
     static_assert(sizeof(std::vector<Type>) == sizeof(std::vector<void *>),
     ^
```

**Comment by Lunarsong** [comment]
Hi! Thank you for the interest :)

I just updated from my local version, only tested with clang with msvc 2017, but I think boolean values might be a problem. My attempt:
```
// Some bools SoA.
SoA<bool> soa_bools;
soa_bools.push_back(false);
soa_bools.push_back(true);
std::cout << "Printing boolean values:\n";
for (int i = 0; i < soa_bools.size(); ++i) {
  std::cout << "(" << i << "): " << soa_bools.get<0>(i) << std::endl;
}
```

However this is an error:
```
include/soa.h:207:12: error: non-const lvalue reference to type 'NthTypeOf<0UL>' (aka 'bool') cannot bind to a temporary of type 'reference' (aka '__bit_reference<std::__1::vector<bool, std::__1::allocator<bool> > >')
    return (*array)[index];
           ^~~~~~~~~~~~~~~
soa_example.cc:106:49: note: in instantiation of function template specialization 'SoA<bool>::get<0>' requested here
    std::cout << "(" << i << "): " << soa_bools.get<0>(i) << std::endl;
```

Isolating the problem:
```
  std::vector<bool> bool_vector;
  bool_vector.push_back(false);
  bool_vector.push_back(true);
  bool& bool_value = bool_vector[0];
  std::cout << "(" << i << "): " << bool_value << std::endl;
```
Reproduces:
```
soa_example.cc:112:9: error: non-const lvalue reference to type 'bool' cannot bind to a temporary of type 'reference' (aka '__bit_reference<std::__1::vector<bool, std::__1::allocator<bool> > >')
  bool& bool_value = bool_vector[0];
        ^    ~~~~~~
1 error generated.
```

So seems like the problem is somewhat deeper...

**Comment by AlexSabourinDev** [comment]
This is almost definitely because of the template specializations of std::vector<bool> which acts differently than other vector types.

http://en.cppreference.com/w/cpp/container/vector_bool

Because of the way `std::vector<bool>` is implemented. It can't return an lvalue reference from the [] operator. This causes it to return an rvalue which you can't store inside of an lvalue reference.

`std::vector<bool>` is a nightmare...

**Comment by AlexSabourinDev** [comment]
I guess a potential solution would be to create a special case for bools... but that sounds pretty annoying.

**Comment by Lunarsong** [comment]
Another solution which I have considered is to not use std::vector, but allocate the memory manually. I considered doing this in the past but decided to start with vector because it was faster to get going.

Bool in the arrays aren't that important for me, so I might not get to it very soon. If you want to have a go at it, please go ahead :) Otherwise consider replacing bool with a uint8_t or int?

**Comment by mean-ui-thread** [comment]
yup, that's precisely what I did. I used mask to store more than one bool. Having no bool is not a big deal. And yes, I agree with @AlexSabourinDev with vector of bools. it's annoying... :weary: 

single memory allocation instead of an array of std::vector? that is so cool! I was reading about exactly that yesterday in this old blog post http://bitsquid.blogspot.ca/2014/09/building-data-oriented-entity-system.html

Anyway, enough distraction. You can go back to swording :crossed_swords:

**Comment by Lunarsong** [comment]
Haha, gamedev it is for me tonight 👩‍💻

Thanks again for opening issues! Please feel free to open more, I am excited to see more interest in this. Data Oriented Design FTW!

P.S. Oh wow, this old article is familiar!

**Comment by mean-ui-thread** [comment]
My pleasure! I am also thrilled and excited to see the Data Oriented movement growing. :grin:
